---

- name: include data center fabric variables
  include_vars: ./intended/structured_configs//{{ inventory_hostname }}.yml
  delegate_to: localhost
  tags:
    - documentation
    - config
    - device_documentation

- name: Generate eos intended configuration
  template:
    src: eos-intended-config.j2
    dest: ./intended/configs/{{ inventory_hostname }}.cfg
  delegate_to: localhost
  register: eosconfig
  tags:
    - documentation
    - config

- name: Generate device documentation
  template:
    src: eos-device-documentation.j2
    dest: ./documentation/devices/{{ inventory_hostname }}.md
  delegate_to: localhost
  tags:
    - documentation
    - config
    - device_documentation