---
# tasks file for eos-config-deploy-cvp
- name: generate intented variables
  inventory_to_container:
    inventory: 'inventory.yml'
    container_root: 'DC1_FABRIC'
    configlet_dir: 'intended_configs'
    configlet_prefix: 'AVD'
    # destination: 'generated_vars/{{inventory_hostname}}.yml'
  register: CVP_VARS

- name: test
  debug:
    msg: '{{CVP_VARS}}'

- name: 'Collecting facts from CVP {{inventory_hostname}}.'
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: 'Create configlets on CVP {{inventory_hostname}}.'
  arista.cvp.cv_configlet:
    cvp_facts: "{{CVP_FACTS.ansible_facts}}"
    configlets: "{{CVP_VARS.CVP_CONFIGLETS}}"
    configlet_filter: ["AVD"]

# - name: "Building Container topology on {{inventory_hostname}}"
#   arista.cvp.cv_container:
#     topology: '{{CVP_VARS.CVP_TOPOLOGY}}'
#     cvp_facts: '{{CVP_FACTS.ansible_facts}}'
#     save_topology: true