---
# tasks file for eos-config-deploy-cvp - state=present
- name: 'Collecting facts from CVP {{inventory_hostname}}.'
  tags: [always]
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: 'Create configlets on CVP {{inventory_hostname}}.'
  tags: [provision]
  arista.cvp.cv_configlet:
    cvp_facts: "{{CVP_FACTS.ansible_facts}}"
    configlets: "{{CVP_VARS.CVP_CONFIGLETS}}"
    configlet_filter: ["{{ configlets_prefix }}"]

- name: "Building Containers topology on {{inventory_hostname}}"
  tags: [provision]
  arista.cvp.cv_container:
    topology: '{{CVP_CONTAINERS}}'
    cvp_facts: '{{CVP_FACTS.ansible_facts}}'
    save_topology: true

- name: 'Refreshing facts from CVP {{inventory_hostname}}.'
  tags: [always]
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: "Configure devices on {{inventory_hostname}}"
  tags: [provision, apply]
  arista.cvp.cv_device:
    devices: "{{CVP_DEVICES}}"
    cvp_facts: '{{CVP_FACTS.ansible_facts}}'
    device_filter: ['{{ device_filter }}']
    state: present
  register: CVP_DEVICES_RESULTS

- name: "Execute pending tasks on {{inventory_hostname}}"
  tags: [apply]
  arista.cvp.cv_task:
    tasks: "{{ CVP_DEVICES_RESULTS.data.tasks }}"
    wait: 720