# H-DC-TENANTS
# Documentation of Tenant specific information - Vlans/VRFs

tenants:

# Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    id: 1
    vrfs:
      Tenant_A_OPZone:
        loopback_range: 10.1.255.0/24
        id: 1
        svis:
          110:
            name: Tenant_A_OPZone_1
            enabled: true
            type: host
            ip_subnet: 10.1.10.0/24
            ip_subnet_secondary: 10.1.100.0/24
          111:
            name: Tenant_A_OPZone_2
            enabled: true
            type: host
            ip_subnet: 10.1.11.0/24

# Tenant B Specific Information - VRFs / VLANs
  Tenant_B:
    id: 2
    vrfs:
      Tenant_B_OPZone:
        loopback_range: 10.2.255.0/24
        id: 1
        svis:
          210:
            name: Tenant_B_OPZone_1
            enabled: true
            type: host
            ip_subnet: 10.2.10.0/24
          211:
            name: Tenant_B_OPZone_2
            enabled: true
            type: host
            ip_subnet: 10.2.11.0/24

# Tenant B Specific Information - VRFs / VLANs
  Tenant_C:
    id: 3
    vrfs:
      Tenant_C_OPZone:
        loopback_range: 10.3.255.0/24
        id: 1
        svis:
          310:
            name: Tenant_C_OPZone_1
            enabled: true
            type: host
            ip_subnet: 10.3.10.0/24
          311:
            name: Tenant_C_OPZone_2
            enabled: true
            type: host
            ip_subnet: 10.3.11.0/24