# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types:  [jinja]
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/pycqa/pylint
    rev: 'pylint-2.6.0'
    hooks:
    - id: pylint # Use pylintrc file in repository
      name: Check for Linting error on Python files
      description: This hook runs pylint.
      types: [python]
      args:
        # Suppress duplicate code for modules header
        - -d duplicate-code

  - repo: https://github.com/adrienverge/yamllint.git
    rev: 'v1.23.0'
    hooks:
    - id: yamllint
      name: Check for Linting error on YAML files
      description: This hook runs yamllint.
      entry: yamllint
      language: python
      types: [file, yaml]
      args: [-c=.github/yamllintrc]
