---
pod_name: DC2_POD1

underlay_p2p_network_summary: 172.17.210.0/24

overlay_loopback_network_summary: 172.16.210.0/24

vtep_loopback_network_summary: 172.18.210.0/24

mlag_ips:
  mlag_peer: 172.19.210.0/24
  leaf_peer_l3: 172.20.210.0/24

l2leaf_inband_management_subnet: 172.21.210.0/24
l2leaf_inband_management_vlan: 4085

super_spine_underlay_p2p_network_summary: 172.16.21.0/24

spine:
  platform: vEOS-LAB
  bgp_as: 65210
  uplinks_to_super_spine_interfaces: [ Ethernet1, Ethernet2 ]
  nodes:
    # Spine also working as EVPN RS
    DC2-POD1-SPINE1:
      id: 1
      mgmt_ip: 192.168.210.1/16
      evpn_role: server
      super_spine_interfaces: [ Ethernet1, Ethernet1 ]
      evpn_route_servers: [ DC1-RS1, DC1-SUPER-SPINE1, DC1-POD1-SPINE1, DC1-POD1-LEAF1A ]
    DC2-POD1-SPINE2:
      id: 2
      evpn_role: none
      mgmt_ip: 192.168.210.2/16
      super_spine_interfaces: [ Ethernet2, Ethernet2 ]
  
# In DC2 we define all variables on specific node / node_group
l3leaf:
  defaults:
    platform: vEOS-LAB
    spines: [ DC2-POD1-SPINE1, DC2-POD1-SPINE2 ]
    uplink_to_spine_interfaces: [ Ethernet1, Ethernet2 ]
    evpn_role: server
    evpn_route_servers: [ DC1-RS1, DC1-SUPER-SPINE1, DC1-POD1-SPINE1, DC1-POD1-LEAF1A ]
  node_groups:
    # Single switch working as underlay L3 router and EVPN RS
    RACK1_SINGLE:
      bgp_as: 65211
      nodes:
        DC2-POD1-LEAF1A:
          id: 1
          mgmt_ip: 192.168.211.1/16
          spine_interfaces: [ Ethernet3, Ethernet3 ]

# In DC2 we define all variables via defaults if possible
l2leaf:
  defaults:
    platform: vEOS-LAB
    parent_l3leafs: [ DC2-POD1-LEAF1A ]
    uplink_interfaces: [ Ethernet1 ]
  node_groups:
    RACK2_SINGLE:
      nodes:
        DC2-POD1-L2LEAF1A:
          id: 1
          mgmt_ip: 192.168.212.1/16
          l3leaf_interfaces: [ Ethernet3 ]
