---
# tasks file for eos_commands_collect

- name: Create output directory for each EOS device
  file:
    path: "{{ commands_backup_dir }}/{{ inventory_hostname }}"
    state: directory

- name: run show commands on remote EOS devices
  eos_command:
    commands: "{{ item }}"
  with_items: "{{ commands_to_collect }}"
  ignore_errors: true
  register: cli_output

- name: save collected commands in text files
  template:
    src: command.j2
    dest: "{{ commands_backup_dir }}/{{ inventory_hostname }}/{{ item.item }}.txt"
  loop: "{{ cli_output.results }}"
  when: '"text_files" in output_format'

- name: Generate markdown report
  include_tasks: "markdown.yml"
  when:
    - '"markdown_report" in output_format'
