---
### Port-Channel Interfaces ###
port_channel_interfaces:
  Port-Channel5:
    description: DC1_L2LEAF1_Po1
    vlans: 110,201
    mode: trunk
    mlag: 5
  Ethernet5:
    peer: DC1-AGG01
    peer_interface: Ethernet1
    peer_type: l2leaf
    description: DC1-AGG01_Ethernet1
    channel_group:
      id: 5
      mode: active

  Port-Channel3:
    description: MLAG_PEER_DC1-LEAF1B_Po3
    vlans: "2-4094"
    mode: trunk
    trunk_groups:
      - LEAF_PEER_L3
      - MLAG
  Ethernet3:
    peer: DC1-LEAF1B
    peer_interface: Ethernet3
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-LEAF1B_Ethernet3
    channel_group:
      id: 3
      mode: active
  Ethernet4:
    peer: DC1-LEAF1B
    peer_interface: Ethernet4
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-LEAF1B_Ethernet4
    channel_group:
      id: 3
      mode: active

  Ethernet1:
    peer: DC1-SPINE1
    peer_interface: Ethernet1
    peer_type: spine
    description: P2P_LINK_TO_DC1-SPINE1_Ethernet1
    mtu: 1500
    type: routed
    ip_address: 172.31.255.1/31

  Ethernet6:
    peer: SRV-POD02
    peer_interface: Eth1
    peer_type: server
    description: SRV-POD02_Eth1
    mode: trunk
    vlans: 110-111,210-211
    profile: ALL
