---
- name: Converge
  hosts: cv_server
  gather_facts: false
  connection: local
  vars:
    root_dir: '{{playbook_dir}}'
  tasks:
    - name: run CVP provisioning
      tags: generate
      import_role:
        name: eos_config_deploy_cvp
      vars:
        container_root: 'DC1_FABRIC'
        configlets_prefix: 'AVD'
        device_filter: 'DC1'
        execute_tasks: false
        state: present
