---
- name: Configure local folders
  hosts: DC1_FABRIC
  gather_facts: false
  connection: local
  vars:
    root_dir: '{{playbook_dir}}'
  tasks:
    - name: create local output folders
      delegate_to: 127.0.0.1
      import_role:
         name: arista.avd.build_output_folders
      run_once: true
    - name: generate intented variables
      import_role:
        name: eos_l3ls_evpn
    - name: generate device intended config and documention
      import_role:
        name: eos_cli_config_gen
