---
- name: validate NTP status
  eos_command:
    commands: "show ntp status"
    waitfor:
      - "result[0] contains 'synchronised to NTP server'"
    retries: 2
    interval: 2
  when: |
    (ntp_server.nodes is defined and ntp_server.nodes is not none)
  ignore_errors: "{{ validation_mode_loose }}"
  tags:
    - avd

- name: validate MLAG status
  eos_command:
    commands: "show mlag detail | json"
    waitfor:
      - "result[0].state eq 'active'"
      - "result[0].negStatus eq 'connected'"
    retries: 2
    interval: 2
  ignore_errors: "{{ validation_mode_loose }}"
  when: |
    (mlag_configuration is defined and mlag_configuration is not none)
  tags:
    - avd
