---

# Hardware Validation Tests

- name: collect power supplies status
  eos_command:
      commands: "show system environment power | json"
  register: system_environment_power
  tags:
    - hardware

- name: validate power supplies status
  assert:
    that:
      - powerSupply.value.state == 'ok'
    quiet: true
  loop: "{{ system environment power.stdout_lines.0.powerSupplies | dict2items }}"
  loop_control:
    loop_var: powerSupply
  ignore_errors: "{{ validation_mode_loose }}"
  register: power_supplies_results
  tags:
    - hardware

- name: collect fan status
  eos_command:
    commands: "show system environment cooling | json"
  register: system_environment_cooling
  tags:
    - hardware

- name: validate fan status (power supplies)
  assert:
    that:
      - powerSupplySlot.status == 'ok'
    quiet: true
  loop: "{{ system_environment_cooling.stdout_lines.0.powerSupplySlots }}"
  loop_control:
    loop_var: powerSupplySlot
  ignore_errors: "{{ validation_mode_loose }}"
  register: fan_power_supplies_results
  tags:
    - hardware

- name: validate fan status (fan tray)
  assert:
    that:
      - fanTraySlot.status == 'ok'
    quiet: true
  loop: "{{ system_environment_cooling.stdout_lines.0.fanTraySlots }}"
  loop_control:
    loop_var: fanTraySlot
  ignore_errors: "{{ validation_mode_loose }}"
  register: fan_tray_status_results
  tags:
    - hardware

- name: validate temperature
  eos_command:
    commands: "show system environment temperature | json"
  ignore_errors: "{{ validation_mode_loose }}"
  register: environment_temperature
  tags:
    - hardware

- name: validate temparature
  assert:
    that:
      - environment_temparature.stdout[0].systemStatus == "temperatureOk"
    quiet: true
  ignore_errors: "{{ validation_mode_loose }}"
  register: environment_temperature_results
  tags:
    - hardware

- name: collect transceivers inventory
  eos_command:
    commands: "show inventory | json"
  register: inventory
  tags:
    - hardware

- name: validate transceivers manufacturers
  assert:
    that:
      - "item.value.mfgName in ['Not Present', 'Arastra, Inc.', 'Arista Networks']"
    quiet: true
  loop: "{{ inventory.stdout_lines.0.xcvrSlots | dict2items }}"
  ignore_errors: "{{ validation_mode_loose }}"
  register: transceiver_inventory_results
  tags:
    - hardware