---

# Hardware Validation Tests

- name: collect power supplies status
  eos_command:
      commands: "show system environment power | json"
  register: power
  tags:
  - hardware

- name: validate power supplies status
  assert:
    that:
      - item.value.state == 'ok'
    quiet: true
  loop: "{{ power.stdout_lines.0.powerSupplies | dict2items }}"
  ignore_errors: "{{ validation_mode_loose }}"
  tags:
  - hardware

- name: collect fan status
  eos_command:
    commands: "show system environment cooling | json"
  register: fan
  tags:
  - hardware

- name: validate fan status (power supplies)
  assert:
    that:
      - item.status == 'ok'
    quiet: true
  loop: "{{ fan.stdout_lines.0.powerSupplySlots }}"
  ignore_errors: "{{ validation_mode_loose }}"
  tags:
  - hardware

- name: validate fan status (fan tray)
  assert:
    that:
      - item.status == 'ok'
    quiet: true
  loop: "{{ fan.stdout_lines.0.fanTraySlots }}"
  ignore_errors: "{{ validation_mode_loose }}"
  tags:
  - hardware

- name: validate temperature
  eos_command:
    commands: "show system environment temperature | json"
    wait_for: result[0].systemStatus eq 'temperatureOk'
  ignore_errors: "{{ validation_mode_loose }}"
  tags:
  - hardware

- name: collect transceivers inventory
  eos_command:
    commands: "show inventory | json"
  register: inventory
  tags:
  - hardware

- name: validate transceivers manufacturers
  assert:
    that:
      - "item.value.mfgName in ['Not Present', 'Arastra, Inc.', 'Arista Networks']"
    quiet: true
  loop: "{{ inventory.stdout_lines.0.xcvrSlots | dict2items }}"
  ignore_errors: "{{ validation_mode_loose }}"
  tags:
  - hardware