---

- name: run show ip route lo1
  eos_command:
    commands: "show ip route {{ loopback1_address }}"
  loop: "{{ loopback1_reachability.loopback1_range }}"
  loop_control:
    loop_var: loopback1_address
  ignore_errors: "{{ eos_validate_state_validation_mode_loose }}"
  when: |
    (loopback1_reachability.loopback1_range is defined and loopback1_reachability.loopback1_range is not none) and
    (type is defined and type == "l3leaf")
  register: loopback1_reachability_state
  tags:
    - loopback1_reachability

- name: Validate lo1 is in routing table
  assert:
    that:
      - loopback1_reachability_test['stdout'][0] | regex_search(loopback1_reachability_test.loopback1_address)
    fail_msg: "{{ loopback1_reachability_test.loopback1_address }} is not in the routing table"
    quiet: true
  loop: "{{ loopback1_reachability_state.results }}"
  loop_control:
    loop_var: loopback1_reachability_test
  ignore_errors: "{{ eos_validate_state_validation_mode_loose }}"
  when: ( loopback1_reachability_test.skipped is not defined )
  register: loopback1_reachability_results
  tags:
    - loopback1_reachability