---
# defaults file for eos_commands_collect

root_dir: '{{ inventory_dir }}'
commands_backup_dir_name: 'commands'
commands_backup_dir: '{{ root_dir }}/{{ commands_backup_dir_name }}'

# list of desired formats. Supported values are markdown, yaml, json and text.
# text: one file per device and show command
# markdown: one report per device
# json: one report per fabric
# yaml: one report per fabric
output_format:
 - text
 - markdown
 # - json
 # - yaml

commands_to_collect:
  - show lldp neighbors
  - show ip interface brief
  - show interfaces description
  - show version
  - show running-config
