galaxy_info:
  author: Arista Ansible Team <ansible@arista.com>
  description: Opiniated Data model for deployment of L3 Leaf and Spine Fabric with VXLAN data-plane with an EVPN Control plane.
  company: Arista Networks
  license: Apache-2.0
  min_ansible_version: 2.9
  galaxy_tags: ['arista', 'network', 'networking', 'eos', 'avd', 'cloudvision', 'cvp']
dependencies: []

