name: Commit check
on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '*'
    paths:
      - 'ansible_collections/arista/avd/**'

jobs:
  'pre-commit':
    name: Run pre-commit validation hooks
    runs-on: ubuntu-latest
    container: avdteam/base:centos-8
    steps:
      - uses: actions/checkout@master
      - name: 'Lint YAML Content'
        run: |
          make pre-commit
