name: Commit check
on:
  push:

jobs:
  'pre-commit':
    name: Run pre-commit validation hooks
    runs-on: ubuntu-latest
    container: avdteam/base:3.6
    steps:
      - uses: actions/checkout@master
      - name: 'Pre Commit run'
        run: |
          make pre-commit
