name: Ansible Molecule CLI CONFIG GEN
on:
  push:
    branches:
      - devel
  pull_request:
    paths:
      - 'ansible_collections/arista/avd/roles/eos_cli_config_gen/tasks/**'
      - 'ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/**'
      - 'ansible_collections/arista/avd/roles/eos_l3ls_evpn/tasks/**'
      - 'ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/**'
      - 'ansible_collections/arista/avd/molecules/**'
      - 'development/requirements**'
      - '.github/workflows/molecule-cli-config-gen.yml'
jobs:
  molecule:
    name: Run CI test for eos_cli_config_gen
    runs-on: ubuntu-latest
      fail-fast: true
      matrix:
        avd_scenario:
          - 'eos_cli_config_gen'
    steps:
      - name: 'set environment variables'
        run: |
          echo "PY_COLORS=1" >> $GITHUB_ENV
          echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development/requirements.txt
          pip install -r development/requirements-dev.txt

      - name: Execute molecule
        run: |
          cd ansible_collections/arista/avd
          molecule test --destroy=never  --scenario-name ${{ matrix.avd_scenario }}
          ls -alR molecule

      - name: Check GIT changes
        run: |
          changes=$(git status --short | wc -l | awk -F " " "{print $1}") ;\
          if [[ $(echo ${changes}| tr -d ' ') == *'0' ]];\
          then echo 'No change' && return 0; else echo 'Has changes' && return 1 ; fi

      - uses: actions/upload-artifact@v1
        with:
          name: molecule-results-${{ matrix.avd_scenario }}
          path: ansible_collections/arista/avd/molecule/${{ matrix.avd_scenario }}
