name: Ansible Molecule
on:
  push:
  pull_request:
    paths:
      - 'ansible_collections/arista/avd/roles/**'
      - 'ansible_collections/arista/avd/molecules/**'
      - 'requirements.txt'
jobs:
  molecule:
    runs-on: ubuntu-latest
    container: avdteam/base:3.6
    env:
      PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
      ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions
    strategy:
      fail-fast: true
      matrix:
        avd_scenario:
          - 'avd-l3ls-ebgp'
          - 'avd-l3ls-ebgp-json'
          - 'avd-l3ls-isis'
          - 'eos-cli-config-gen'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Run molecule action
      #   uses: inetsix/molecule-collection-actions@master
      #   with:
      #     molecule_parentdir: 'ansible_collections/arista/avd'
      #     molecule_command: 'test'
      #     molecule_args: '-s ${{ matrix.avd_scenario }}'
      #     pip_file: 'requirements.txt'

      - name: Execute molecule
        run: |
          cd ansible_collections/arista/avd
          molecule test --scenario-name ${{ matrix.avd_scenario }}

      - uses: actions/upload-artifact@v1
        with:
          name: molecule-results-${{ matrix.avd_scenario }}
          path: ansible_collections/arista/avd/molecule/${{ matrix.avd_scenario }}
